const locations = {
    Herat: {
        cityDistricts: [ "ناحیه ۱", "ناحیه ۲", "ناحیه ۳", "ناحیه ۴", "ناحیه ۵", "ناحیه ۶", "ناحیه ۷",  "ناحیه ۸",  "ناحیه ۹",  "ناحیه ۱۰"],
        ruralDistricts: ["Injil",  "Guzara",  "Kushk",  "Karukh", "Shindand", "Kushki Kuhna", "Gulran", "Ghoryan", "Kohsan", "Obe","Zinda Jan",   "Zawal"],
    },
    Kabul: {
        cityDistricts: [ "District 1", "District 2", "District 3", "District 4", "District 5", "District 6", "District 7", "District 8", "District 9", "District 10",],
        ruralDistricts: ["Kabul", "Paghman", "Bagrami", "Char Asiab", "Deh Sabz",  "Farza", "Guldara", "Istalif", "Shakardara",  "Surobi", ],
    },
    Nangarhar: {
        cityDistricts: [],
        ruralDistricts: [ "Jalalabad", "Haska Meyna", "Shinwar", "Achin", "Bihsud", "Chaparhar", "Darai Nur", "Bati Kot", "Dur Baba", "Goshta", "Hisarak","Kama", "Khogyani", "Kot", "Kuz Kunar", "Lal Pur", "Momand Dara", "Nazyan", "Pachir Aw Agam", "Rodat", "Sherzad","Surkh Rod",],
    },
    Kandahar: {
    cityDistricts: [
      "District 1",
      "District 2",
      "District 3",
      "District 4",
      "District 5",
      "District 6",
      "District 7",
      "District 8",
      "District 9",
      "District 10",
    ],
    ruralDistricts: [
      "Kandahar",
      "Dand",
      "Shah Wali Kot",
      "Maiwand",
      "Zherai",
      "Spin Boldak",
      "Arghandab",
      "Khakrez",
      "Ghorak",
      "Nesh",
      "Registan",
      "Panjwai",
      "Daman",
      "Nawa",
      "Shahjoy",
      "Takht-e-Pul",
      "Baldak",
      "Pato",
      "Miyanishin",
    ],
  },
  Balkh: {
    cityDistricts: [],
    ruralDistricts: [
      "Balkh",
      "Charbolak",
      "Charkint",
      "Chimtal",
      "Dawlatabad",
      "Dihdadi",
      "Kaldar",
      "Khulm",
      "Kishindih",
      "Marmul",
      "Mazar-e-Sharif",
      "Sholgara",
      "Saysad",
      "Zari",
      "Nahr-e-Shahi",
      "Nawmish",
      "Madan-e-Sar",
      "Koh-e-Naw",
      "Omarkhel",
      "Hesar-e-Shahi",
    ],
  },
  Badakhshan: {
    cityDistricts: [],
    ruralDistricts: [
      "Faizabad",
      "Shahr-e-Buzurg",
      "Jurm",
      "Wakhan",
      "Argo",
      "Kohistan",
      "Panjshir",
      "Yaftal",
      "Tishkan",
      "Raghistan",
      "Maimai",
      "Shahr-e-Gonbad",
      "Khash",
      "Khanabad",
      "Nusay",
      "Chah Ab",
      "Barg-e-Matal",
    ],
  },
  Kunar: {
    cityDistricts: [],
    ruralDistricts: [
      "Asadabad", // مرکز
      "Narai",
      "Narang",
      "Dangam",
      "Chawkay",
      "Khas Kunar",
      "Marawara",
      "Nurgal",
      "Shigal",
      "Wata Pur",
      "Sawkai",
      "Ghazi Abad",
      "Shegal",
      "Nari",
      "Noorgul",
      "Sarkani",
      "Bar Kunar",
      "Peche Dara",
      "Manogai",
      "Chapa Dara",
    ],
  },
  Ghazni: {
    cityDistricts: [],
    ruralDistricts: [
      "Ghazni", // مرکز
      "Andar",
      "Deh Yak",
      "Ab Band",
      "Giro",
      "Gilan",
      "Jaghatu",
      "Jaghori",
      "Khwaja Omari",
      "Malistan",
      "Muqur",
      "Nawa",
      "Nawur",
      "Qarabagh",
      "Rashidan",
      "Waghaz",
      "Zana Khan",
      "Zebak",
      "Ajristan",
      "Waghaz",
    ],
  },
  Paktia: {
    cityDistricts: [],
    ruralDistricts: [
      "Gardez",
      "Zurmat",
      "Ahmad Aba",
      "Ahmad Khel",
      "Dand Patan",
      "Lazha Mangal",
      "Chamkani",
      "Jani Khel",
      "Lajah Ahmad Khel",
      "Lajah Mangal",
      "Mirzaka",
      "Sayed Karam",
      "Shwak",
      "Zazi Aryob",
      "Zazi Maidan",
      "Wuza Zadran",
      "Jaji Aryoub",
      "Shahikhel",
      "Aryob Zazi",
      "Shwak",
    ],
  },

  Faryab: {
    cityDistricts: [],
    ruralDistricts: [
      "Maymana",
      "Almar",
      "Andkhoy",
      "Dawlatabad",
      "Ghormach",
      "Khani Chahar Bagh",
      "Pashtun Kot",
      "Qaramqol",
      "Qaysar",
      "Shirin Tagab",
      "Belcheragh",
      "Gurziwan",
      "Kohistan",
      "Khwaja Sabz Posh",
      "Qaisar",
      "Sherin Tagab",
      "Gurziwan",
      "Khani Chaharbagh",
      "Maimana",
      "Ghormach",
    ],
  },
  Takhar: {
    cityDistricts: [],
    ruralDistricts: [
      "Taloqan", // مرکز ولایت
      "Baharak",
      "Bangi",
      "Chah Ab",
      "Darqad",
      "Dashti Qala",
      "Farkhar",
      "Khwaja Bahauddin",
      "Khwaja Ghar",
      "Namaka Ab",
      "Rustaq",
      "Warsaj",
      "Yangi Qala",
      "Ishkamish",
      "Hazar Sumuch",
      "Qala-e-Sangi",
      "Zar Khan", 
      "Kandahariha", 
      "Kuf Ab", 
    ],
  },

  Kunduz: {
    cityDistricts: [],
    ruralDistricts: [
      "Kunduz", 
      "Ali Abad",
      "Chahar Dara",
      "Dasht-e-Archi",
      "Imam Sahib",
      "Khan Abad",
      "Qalay-e-Zal",
      "Sayed Abad",
      "Talawka",
      "Baba Tangi",
      "Bazari",
      "Qalacha",
      "Shor Tepa",
      "Pul Rangin",
      "Chil Dukhtaran",
      "Tapay-e-Bagrami",
      "Sardar",
      "Jangal Bashi",
      "Bangi Tapa",
    ],
  },
  Bamyan: {
    cityDistricts: [],
    ruralDistricts: [
      "Bamyan", 
      "Yakawlang",
      "Yakawlang 2", 
      "Saighan",
      "Shibar",
      "Waras",
      "Panjab",
      "Kahmard",
      "Shebar", 
      "Gandab", 
      "Sangtakht", 
      "Baba",
      "Do Ab",
      "Qala-e-Sangar",
      "Bamyan Bala",
      "Qol-e-Barfi",
      "Sorkh Qol",
      "Tatar",
      "Bandi Amir",
      "Qazan",
    ],
  },

  Baghlan: {
    cityDistricts: [],
    ruralDistricts: [
      "Pul-e-Khumri", 
      "Baghlan-e-Markazi",
      "Dahana-e-Ghori",
      "Doshi",
      "Andarab",
      "Khost Wa Fereng",
      "Nahrin",
      "Burka",
      "Tala Wa Barfak",
      "Khulmi",
      "Surkh Kotal",
      "Qades",
      "Zaman Khel",
      "Shashan", 
      "Zamanabad",
      "Pule Rangin", 
      "Dand-e-Ghori", 
      "Chashma Sher",
      "Qara Khel",
      "Kata Khel",
    ],
  },
  Zabul: {
    cityDistricts: [],
    ruralDistricts: [
      "Qalat",
      "Shahr-e-Safa",
      "Mizan",
      "Shah Joy",
      "Khan-e-Wali",
      "Khakrez",
      "Registan",
      "Miyanishin",
      "Nad Ali",
      "Spin Boldak",
      "Dand",
      "Zhari",
      "Shahjoi",
      "Zabul",
      "Ghorak",
    ],
  },
  Nuristan: {
    cityDistricts: [],
    ruralDistricts: [
      "Parun",
      "Kamdesh",
      "Doab",
      "Wama",
      "Nuristan",
      "Mandol",
      "Gorbuz",
      "Dara-e-Noor",
      "Pachir Aw Agam",
      "Ribat",
      "Narang",
      "Barg-e-Matal",
      "Dara-e-Pech",
      "Shigal",
      "Baba Wali",
    ],
  },
  Logar: {
    cityDistricts: [],
    ruralDistricts: [
      "Pul-e-Alam",
      "Kharwar",
      "Mohammad Agha",
      "Charkh",
      "Azra",
      "Baraki Barak",
      "Khushi",
      "Koot",
    ],
  },
  Khost: {
    cityDistricts: [],
    ruralDistricts: [
      "Khost",
      "Sabari",
      "Mandozai",
      "Shamal",
      "Gul Khel",
      "Tani",
      "Zazai Maidan",
      "Spera",
      "Gardan",
      "Kherwar",
    ],
  },
  Sar_e_Pol: {
    cityDistricts: [],
    ruralDistricts: [
      "Sar-e Pol",
      "Sayad",
      "Kohistan",
      "Balkhab",
      "Sancharak",
      "Sholgara",
      "Gosfandi",
      "Kishindih",
    ],
  },

  Helmand: {
    cityDistricts: [],
    ruralDistricts: [
      "Lashkar Gah",
      "Nawa",
      "Sangin",
      "Musa Qala",
      "Kajaki",
      "Nawzad",
      "Gereshk",
      "Dishu",
      "Marja",
      "Nahr-e-Saraj",
      "Garmsir",
      "Nahr-e-Shahi",
      "Washir",
    ],
  },
  Laghman: {
    cityDistricts: [],
    ruralDistricts: [
      "Mehtarlam", 
      "Alingar",
      "Alishang",
      "Dawlat Shah",
      "Badpakh",
      "Qarghayi",
    ],
  },
  Samangan: {
    cityDistricts: [],
    ruralDistricts: [
      "Aybak", 
      "Hazrat Sultan",
      "Ruyi Du Ab",
      "Dara-i-Suf Bala",
      "Dara-i-Suf Payin",
      "Khuram Wa Sarbagh",
      "Feroz Nakhchir",
    ],
  },
  Nimroz: {
    cityDistricts: [],
    ruralDistricts: [
      "Zaranj", 
      "Chakhansur",
      "Kang",
      "Khash Rod",
      "Charborjak",
    ],
  },
  Ghor: {
    cityDistricts: [],
    ruralDistricts: [
      "Firoz Koh", 
      "Chaghcharan", 
      "Shahrak",
      "Taywara",
      "Pasaband",
      "Dawlatyar",
      "Charsada",
      "Tulak",
      "Saghar",
      "Lal wa Sarjangal",
    ],
  },
  Panjshir: {
    cityDistricts: [],
    ruralDistricts: [
      "Bazarak", 
      "Rukha",
      "Shotul",
      "Paryan",
      "Khenj",
      "Anaba",
      "Darah",
    ],
  },
  Urozgan: {
    cityDistricts: [],
    ruralDistricts: [
      "Tarinkot", 
      "Chora",
      "Khas Urozgan",
      "Deh Rawod",
    ],
  },
  Daykundi: {
    cityDistricts: [],
    ruralDistricts: [
      "Nili", 
      "Kijran",
      "Khadir",
      "Sangi Takht",
      "Miramor",
      "Shahristan",
      "Ashtarlay",
      "Gizab", 
    ],
  },
  Wardak: {
    cityDistricts: [],
    ruralDistricts: [
      "Maidan Shahr", 
      "Sayd Abad",
      "Chak",
      "Jaghatu",
      "Nirkh",
      "Day Mirdad",
      "Hesa Awal Behsud",
      "Hesa Duwum Behsud",
    ],
  },
  Farah: {
    cityDistricts: [],
    ruralDistricts: [
      "Farah City", 
      "Anar Dara",
      "Bala Buluk",
      "Bakwa",
      "Gulistan",
      "Khak-e-Safid",
      "Lash wa Juwayn",
      "Pur Chaman",
      "Shib Koh",
    ],
  },
  Badghis: {
    cityDistricts: [], 
    ruralDistricts: [
      "Qala-e-Naw",
      "Ab Kamari",
      "Ghormach",
      "Jawand",
      "Muqur",
      "Bala Murghab",
    ],
  },
  Jawzjan: {
    cityDistricts: ["Sheberghan"], 
    ruralDistricts: [
      "Aqcha",
      "Darzab",
      "Khamyab",
      "Khwaja Du Koh",
      "Mardyan",
      "Qush Tepa",
      "Fayzabad",
      "Mangjik",
    ],
  },

  Parwan: {
    cityDistricts: ["Charikar"], 
    ruralDistricts: [
      "Bagram",
      "Salang",
      "Shinwari",
      "Ghorband",
      "Jabul Saraj",
      "Sayed Khel",
      "Surkh Parsa",
      "Sheikh Ali",
      "Koh-e-Safi",
    ],
  },
  Kapisa: {
    cityDistricts: ["Mahmud Raqi"], 
    ruralDistricts: [
      "Nijrab",
      "Tagab",
      "Kohistan",
      "Alasay",
      "Hisa-e-Awal Kohistan",
      "Hisa-e-Duwum Kohistan",
    ],
  },
  Paktika: {
    cityDistricts: [],
    ruralDistricts: [
      "Sharana",
      "Urgun",
      "Barmal",
      "Dand Patan",
      "Gayan",
      "Zazai Aryub",
      "Khost Wa Fereng",
      "Jani Khel",
      "Chamkani",
      "Shwak",
      "Zurmat",
      "Ahmad Aba",
      "Ahmad Khel",
      "Lazha Mangal",
      "Mirzaka",
      "Sayed Karam",
      "Lajah Ahmad Khel",
      "Lajah Mangal",
      "Zazi Maidan",
      "Shahikhel",
    ],
  },
};

export default locations;
