const postProduct =[
  {
    id: 1,
    seller: "محمد کریمی",
    image: "/image/ring.jpg",
    cat: "انگشتر فیروزه",
    postedAgo: "2 days ago",
    location: "دارلمان عقب کفایت سنتر, Municipal District 6, Kabul",
    price: 4500,
    // currency: "؋",
    type: "New",
  },
  {
    id: 2,
    seller: "dev genius",
    image: "/image/car.jpg",
    cat: "موتر تیزرفتار",
    postedAgo: "2 days ago",
    location: "sldkfj,Municipal District 13, kandahar",
    price: 500000,
    // currency: "؋",
    type: "Used",
  },
  {
    id: 3,
    seller: "کلچه وطنی",
    image: "/image/کلچه وطنی.jpg",
    cat: "کلچه وطنی",
    postedAgo: "9 days ago",
    location: "دشت برچی, Municipal District 13, herat",
    price: 100,
    // currency: "؋",
    type: "New",
  },
  {
    id: 4,
    seller: "ganjyab",
    image: "/image/juse.jpeg",
    cat: "جوس سیب",
    postedAgo: "9 days ago",
    location: "سرای, registan, balkh",
    price: 90,
    // currency: "؋",
    type: "New",
  },
{
  id: 5,
  seller: "mohammad karimi",
       image: "/image/ring.jpg",
    cat: "انگشتر فیروزه",
  postedAgo: "22 days ago",
  location: "nangarhar",
  price: 1000,
//   currency: "؋",
  type: "New"
},
  {
    id: 6,
    seller: "ganjyab",
    image: "/image/caw.jpeg",
    cat: "گاو برای قربانی",
    postedAgo: "12 days ago",
    location: "خیرخانه 315, Municipal District 17, kunduz",
    price: 85000,
    // currency: "؋",
    type: "New",
  },
  {
    id: 7,
    seller: "ganjyab",
    image: "/image/car3.jpeg",
    cat: "موتر جدید",
    postedAgo: "12 days ago",
    location: "سرای, registan, bamyan",
    price: 50000,
    // currency: "؋",
    type: "New",
  },
  {
    id: 8,
    seller: "Posted from Facebook",
    image: "/image/car2.jpeg",
    cat: "موتر سیا سفید",
    postedAgo: "12 days ago",
    location: "سرکوتل,Municiple District 17, parwan",
    price: 500000,
    // currency: "$",
    type: "Used",
  }
]
export default  postProduct;